### ISSUE TITLE
OverflowException when build and run as native x64

### ISSUE THREAD

**Issue by Nozziel** [dblock/resourcelib#27]
various calls that use IntPtr do conversions to .ToInt32() now throw OverflowExceptions.

for example:
return new IntPtr(lpRes.ToInt32() + _header.Header.wLength);

Solution A
replace the .ToInt32() to .ToInt64() but this might slow down certain calls on x86 
return new IntPtr(lpRes.ToInt64() + _header.Header.wLength);

Solution B
Most of the time it concerns IntPtr addition, in .Net 4 you can also do this without the conversions
return IntPtr.Add(lpRes, _header.Header.wLength);

Uncovered when trying to use VersionResource to save new version info to a file.

Edit: found in version 1.4

**Comment by Nozziel** [comment]
It appears most of these issues have already been addressed in #10 but these are not yet release in the current download v1.4

issue #10: https://github.com/dblock/resourcelib/issues/10

**Comment by dblock** [comment]
@icnocop Maybe you can cut a release after #26 is merged? I will eventually get to this too.

**Comment by dblock** [comment]
@Nozziel When you say "most", are there issues you're seeing that are still present? Would love fixes/PRs/tests.

**Comment by Nozziel** [comment]
Yeah, I wrote most; I only use VersionResource class, so I only tested that but I did some further investigation and it seems all IntPtr.ToInt32() have been changed to ToInt64() :+1:
